repos:
  # Python backend hooks
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.7.13
    hooks:
      - id: uv-lock
        files: ^backend/
        args: [--directory, backend]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.13
    hooks:
      - id: ruff-check
        args: [ --fix ]
        files: ^backend/
      - id: ruff-format
        files: ^backend/

  # Frontend hooks
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        files: ^frontend/.*\.(js|jsx|ts|tsx|json|css|md|yaml|yml)$
        args:
          - --config=frontend/.prettierrc
          - --ignore-path=frontend/.prettierignore
          - --write